### ISSUE TITLE
unclear `create_mapping` functionality

### ISSUE THREAD

**Issue by josejimenezluna** [microsoft/molucn#20]
https://github.com/microsoft/molucn/blob/506e10b3f700c8dc4cc9fbbc1c267fc3a42a3c28/molucn/evaluation/compare_bench_color.py#L21

If you want canonical ordering of the folders you can just use `sorted`

**Comment by k-amara** [comment]
I have a subset list of the targets - that's why I need to keep track of the indices (some are skip)
Maybe we can see if there is a more simple way
